### ISSUE TITLE
Brokes the Notes module in NextCloud25

### ISSUE THREAD

**Issue by kolpakovag** [Nagold/files_staticmimecontrol#7]
While editing notes in Nextcloud25 with activated some other applications gives the error:
HTTP 500 (OCP\Files\ForbiddenException) (can not save notes)
I disable the application "files_staticmimecontrol" and this helps.
With default installation of Nextcloud 25 seems all ok.

**Comment by Apfelwurm** [comment]
This is currently to be expected, since this app only aims to be used for files. I guess you have to whitelist the txt mime type for that.
Can you please post the full error and you're json config?
I will take a look on how to configure it (or fix it) to make that work

**Comment by kolpakovag** [comment]
Answer quickly. ) Large useless json? I can describe in all words how to modeling this situation. It is a test configuration of Nextcloud25, installed from web-installer, with ALL available VERIFIED 214 plugins on Debian 10 (mysql 8.0, PHP 8.1). I decided to enable all, then disable broken and try necessary. Now it`s for home using. I am not planning to attach php-debugger just now.

> This is currently to be expected, since this app only aims to be used for files. I guess you have to whitelist the txt mime type

**Comment by Apfelwurm** [comment]
No, not useless :D I just want you're staticmimecontrol.json (or however you have named it in youre case) and the full error messages that appear in https://yourecloud.tdl/settings/admin/logging when you try to save a note.

**Comment by Apfelwurm** [comment]
And just to be clear, you should only use this plugin if you know why you  want to use it. Its designed with full restriction for users in mind. If only you use you're cloud, its pointless.
